name: my workflow
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: '3.8'
      - name: "Install clang-format"
        run: sudo apt install clang-format
      - name: "Run clang-format"
        run: clang-format src/* tests/* --dry-run -Werror
